package ru.agrointellect.remote.dto

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName

class TableFarmSummaryHistory : Table {

    override val datesCount = 2

    override val columns: List<Column>
        get() = listOf(
            Column("№ лактации стада", items.map { Row(it.date, it.avgLactNum ?: "0") }),
            Column("День доения", items.map { Row(it.date, it.avgDaysInMilk ?: "0") }),
            Column("День доения 1 лактации", items.map { Row(it.date, it.avgDaysInMilk1Lact ?: "0") }),
            Column("День доения 2 лактации", items.map { Row(it.date, it.avgDaysInMilk2Lact ?: "0") }),
            Column("День доения лактации > 2", items.map { Row(it.date, it.avgDaysInMilkOver2Lact ?: "0") }),
            Column("Сервис-период", items.map { Row(it.date, it.avgOpenDays ?: "0") }),
            Column("Сервис-период 1 лактации", items.map { Row(it.date, it.avgOpenDays1Lact ?: "0") }),
            Column("Сервис-период 2 лактации", items.map { Row(it.date, it.avgOpenDays2Lact ?: "0") }),
            Column("Сервис-период лактации > 2", items.map { Row(it.date, it.avgOpenDaysOver2Lact ?: "0") }),
            Column("Кол-во дней в сухостое", items.map { Row(it.date, it.avgDryDays ?: "0") }),
            Column("День стельности коров", items.map { Row(it.date, it.avgPregnantDaysCows ?: "0") }),
            Column("День стельности нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Межотельный интервал", items.map { Row(it.date, it.a ?: "0") }),
            Column("Интервал между осеменениями коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Интервал между осеменениями телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дней в госпитале", items.map { Row(it.date, it.a ?: "0") }),
            Column("День доения 1-го осеменения коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Возраст 1-го осеменения телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Возраст 1-го отела", items.map { Row(it.date, it.a ?: "0") }),
            Column("День доения при пике", items.map { Row(it.date, it.a ?: "0") }),
            Column("День доения при пике 1 лактации", items.map { Row(it.date, it.a ?: "0") }),
            Column("День доения при пике 2 лактации", items.map { Row(it.date, it.a ?: "0") }),
            Column("День доения при пике лактации > 2", items.map { Row(it.date, it.a ?: "0") }),
            Column("Фуражных коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("% дойных в стаде", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 1 лактации", items.map { Row(it.date, it.a ?: "0") }),
            Column("% 1 лактации в дойных", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 1 лактации 0-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 1 лактации 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 1 лактации 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 1 лактации > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 2 лактации", items.map { Row(it.date, it.a ?: "0") }),
            Column("% 2 лактации в дойных", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 2 лактации 0-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 2 лактации 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 2 лактации 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров 2 лактации > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров лактации > 2", items.map { Row(it.date, it.a ?: "0") }),
            Column("% лактации > 2 в дойных", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров лактации > 2 0-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров лактации > 2 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров лактации > 2 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Дойных коров лактации > 2 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Стельных коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("% стельных в стаде", items.map { Row(it.date, it.a ?: "0") }),
            Column("Сухостойных коров всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("% сухостойных в стаде", items.map { Row(it.date, it.a ?: "0") }),
            Column("Сухостойных коров 1 фазы", items.map { Row(it.date, it.a ?: "0") }),
            Column("Сухостойных коров 2 фазы", items.map { Row(it.date, it.a ?: "0") }),
            Column("Телок всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Телок 0-2 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Телок 2-6 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Телок 6-12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Телок > 12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Нетелей всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Нетелей 2 фазы", items.map { Row(it.date, it.a ?: "0") }),
            Column("Быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("Осеменений коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Осеменений телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Выявлено стельных коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Выявлено стельных телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Запущено коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Отелов всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Родилось живых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Родилось живых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("Родилось мертвых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Родилось мертвых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("% мертворожденности", items.map { Row(it.date, it.a ?: "0") }),
            Column("% рождаемости телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Отелов от нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("От нетелей родилось живых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("От нетелей родилось живых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("От нетелей родилось мертвых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("От нетелей родилось мертвых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("% мертворожденности от нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("% рождаемости телок от нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Отелов от коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("От коров родилось живых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("От коров родилось живых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("От коров родилось мертвых телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("От коров родилось мертвых быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("% мертворожденности от коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("% рождаемости телок от коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Абортировало коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Абортировало нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Мастит голов за месяц коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Хромота голов за месяц коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Хромота голов за месяц телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Задержаний последа лактация", items.map { Row(it.date, it.a ?: "0") }),
            Column("% задержаний последа у нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Задержаний последа лактация > 1", items.map { Row(it.date, it.a ?: "0") }),
            Column("% задержаний последа у коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Задержаний последа всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("% задержаний последа", items.map { Row(it.date, it.a ?: "0") }),
            Column("Парезов лактация 1", items.map { Row(it.date, it.a ?: "0") }),
            Column("% парезов у нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Парезов лактация > 1", items.map { Row(it.date, it.a ?: "0") }),
            Column("% парезов у коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Парезов всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("% парезов", items.map { Row(it.date, it.a ?: "0") }),
            Column("Кетозов лактация 1", items.map { Row(it.date, it.a ?: "0") }),
            Column("% кетозов у нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Кетозов лактация > 1", items.map { Row(it.date, it.a ?: "0") }),
            Column("% кетозов у коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Кетозов всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("% кетозов", items.map { Row(it.date, it.a ?: "0") }),
            Column("Метритов", items.map { Row(it.date, it.a ?: "0") }),
            Column("% метритов", items.map { Row(it.date, it.a ?: "0") }),
            Column("Переводов коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Переводов телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Вакцинация коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Вакцинация телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Расчистка копыт коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Расчистка копыт телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 1 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация 2 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров лактация > 2 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа коров всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа телок 0-2 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа телок 2-6 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа телок 6-12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа телок > 12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа телок всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Продажа быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 1 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация 2 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 0-10 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 11-30 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 31-60 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 61-120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 > 120 ДД", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров лактация > 2 всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж коров всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж телок 0-2 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж телок 2-6 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж телок 6-12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж телок > 12 мес", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж телок всего", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж нетелей", items.map { Row(it.date, it.a ?: "0") }),
            Column("Падеж быков", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс выявления охоты коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс выявления охоты телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс оплодотворяемости коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс оплодотворяемости телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс стельности коров", items.map { Row(it.date, it.a ?: "0") }),
            Column("Индекс стельности телок", items.map { Row(it.date, it.a ?: "0") }),
            Column("Доз семени на стельную корову", items.map { Row(it.date, it.a ?: "0") }),
            Column("Доз семени на стельную телку", items.map { Row(it.date, it.a ?: "0") }),
            Column("Валовой надой", items.map { Row(it.date, it.a ?: "0") }),
            Column("Надой 1 ф/к", items.map { Row(it.date, it.a ?: "0") }),
            Column("Надой 1 д/к", items.map { Row(it.date, it.a ?: "0") }),
            Column("KPI кормления", items.map { Row(it.date, it.a ?: "0") })
        )

    private fun map() {
        items.map { Row(it.date, it.a ?: "0") }
    }

    @SerializedName("rpt_farm_summary_history")
    @Expose
    lateinit var items: List<RptFarmSummaryHistory>
}