package ru.agrointellect.remote.dto

import com.google.gson.annotations.Expose
import com.google.gson.annotations.SerializedName
import ru.agrointellect.screen.report.Column
import ru.agrointellect.screen.report.Row
import ru.agrointellect.screen.report.Table

@Suppress("SpellCheckingInspection")
class TableFarmSummaryHistory : Table {

    override val columns: List<Column>
        get() = listOf(
            Column("№ лактации стада", mapByDate("avgLactNum")),
            Column("День доения", mapByDate("avgDaysInMilk")),
            Column("День доения 1 лактации", mapByDate("avgDaysInMilk1Lact")),
            Column("День доения 2 лактации", mapByDate("avgDaysInMilk2Lact")),
            Column("День доения лактации > 2", mapByDate("avgDaysInMilkOver2Lact")),
            Column("Сервис-период", mapByDate("avgOpenDays")),
            Column("Сервис-период 1 лактации", mapByDate("avgOpenDays1Lact")),
            Column("Сервис-период 2 лактации", mapByDate("avgOpenDays2Lact")),
            Column("Сервис-период лактации > 2", mapByDate("avgOpenDaysOver2Lact")),
            Column("Кол-во дней в сухостое", mapByDate("avgDryDays")),
            Column("День стельности коров", mapByDate("avgPregnantDaysCows")),
            Column("День стельности нетелей", mapByDate("avgPregnantDaysHeifers")),
            Column("Межотельный интервал", mapByDate("avgCalvIntDays")),
            Column("Интервал между осеменениями коров", mapByDate("avgInsemIntDaysCows")),
            Column("Интервал между осеменениями телок", mapByDate("avgInsemIntDaysHeifers")),
            Column("Дней в госпитале", mapByDate("avgInHospDays")),
            Column("День доения 1-го осеменения коров", mapByDate("avgFirstInsemDimCows")),
            Column("Возраст 1-го осеменения телок", mapByDate("avgFirstInsemAgeHeifers")),
            Column("Возраст 1-го отела", mapByDate("avgFirstCalvAge1Lact")),
            Column("День доения при пике", mapByDate("avgMilkPeakDays")),
            Column("День доения при пике 1 лактации", mapByDate("avgMilkPeakDays1Lact")),
            Column("День доения при пике 2 лактации", mapByDate("avgMilkPeakDays2Lact")),
            Column("День доения при пике лактации > 2", mapByDate("avgMilkPeakDaysOver2Lact")),
            Column("Фуражных коров", mapByDate("hrdCowsAll")),
            Column("Дойных коров всего", mapByDate("hrdCowsLactAll")),
            Column("% дойных в стаде", mapByDate("hrdCowsLactAllPcnt")),
            Column("Дойных коров 1 лактации", mapByDate("hrdCowsLact1All")),
            Column("% 1 лактации в дойных", mapByDate("hrdCowsLact1Pcnt")),
            Column("Дойных коров 1 лактации 0-30 ДД", mapByDate("hrdCowsLact1030")),
            Column("Дойных коров 1 лактации 31-60 ДД", mapByDate("hrdCowsLact13160")),
            Column("Дойных коров 1 лактации 61-120 ДД", mapByDate("hrdCowsLact161120")),
            Column("Дойных коров 1 лактации > 120 ДД", mapByDate("hrdCowsLact1O120")),
            Column("Дойных коров 2 лактации", mapByDate("hrdCowsLact2All")),
            Column("% 2 лактации в дойных", mapByDate("hrdCowsLact2Pcnt")),
            Column("Дойных коров 2 лактации 0-30 ДД", mapByDate("hrdCowsLact2030")),
            Column("Дойных коров 2 лактации 31-60 ДД", mapByDate("hrdCowsLact23160")),
            Column("Дойных коров 2 лактации 61-120 ДД", mapByDate("hrdCowsLact261120")),
            Column("Дойных коров 2 лактации > 120 ДД", mapByDate("hrdCowsLact2O120")),
            Column("Дойных коров лактации > 2", mapByDate("hrdCowsLactO2All")),
            Column("% лактации > 2 в дойных", mapByDate("hrdCowsLactO2Pcnt")),
            Column("Дойных коров лактации > 2 0-30 ДД", mapByDate("hrdCowsLactO2030")),
            Column("Дойных коров лактации > 2 31-60 ДД", mapByDate("hrdCowsLactO23160")),
            Column("Дойных коров лактации > 2 61-120 ДД", mapByDate("hrdCowsLactO261120")),
            Column("Дойных коров лактации > 2 > 120 ДД", mapByDate("hrdCowsLactO2O120")),
            Column("Стельных коров", mapByDate("hrdCowsPregAll")),
            Column("% стельных в стаде", mapByDate("hrdCowsPregPcnt")),
            Column("Сухостойных коров всего", mapByDate("hrdCowsDryAll")),
            Column("% сухостойных в стаде", mapByDate("hrdCowsDryPcnt")),
            Column("Сухостойных коров 1 фазы", mapByDate("hrdCowsDryF1")),
            Column("Сухостойных коров 2 фазы", mapByDate("hrdCowsDryF2")),
            Column("Телок всего", mapByDate("hrdHeifersAll")),
            Column("Телок 0-2 мес", mapByDate("hrdHeifers02")),
            Column("Телок 2-6 мес", mapByDate("hrdHeifers26")),
            Column("Телок 6-12 мес", mapByDate("hrdHeifers612")),
            Column("Телок > 12 мес", mapByDate("hrdHeifersO12")),
            Column("Нетелей всего", mapByDate("hrdPheifersAll")),
            Column("Нетелей 2 фазы", mapByDate("hrdPheifersF2")),
            Column("Быков", mapByDate("hrdBulls")),
            Column("Осеменений коров", mapByDate("evtInsemCows")),
            Column("Осеменений телок", mapByDate("evtInsemHeifers")),
            Column("Выявлено стельных коров", mapByDate("evtGotPregCows")),
            Column("Выявлено стельных телок", mapByDate("evtGotPregHeifers")),
            Column("Запущено коров", mapByDate("evtDryCows")),
            Column("Отелов всего", mapByDate("evtCalvTotal")),
            Column("Родилось живых телок", mapByDate("evtCalvAliveHeifers")),
            Column("Родилось живых быков", mapByDate("evtCalvAliveBulls")),
            Column("Родилось мертвых телок", mapByDate("evtCalvDeadHeifers")),
            Column("Родилось мертвых быков", mapByDate("evtCalvDeadBulls")),
            Column("% мертворожденности", mapByDate("evtCalvDeadAllPcnt")),
            Column("% рождаемости телок", mapByDate("evtCalvAliveHeifersAllPcnt")),
            Column("Отелов от нетелей", mapByDate("evtCalvTotalPheifers")),
            Column("От нетелей родилось живых телок", mapByDate("evtCalvAliveHeifersPheifers")),
            Column("От нетелей родилось живых быков", mapByDate("evtCalvAliveBullsPheifers")),
            Column("От нетелей родилось мертвых телок", mapByDate("evtCalvDeadHeifersPheifers")),
            Column("От нетелей родилось мертвых быков", mapByDate("evtCalvDeadBullsPheifers")),
            Column("% мертворожденности от нетелей", mapByDate("evtCalvDeadPheifersPcnt")),
            Column("% рождаемости телок от нетелей", mapByDate("evtCalvAliveHeifersPheifersPcnt")),
            Column("Отелов от коров", mapByDate("evtCalvTotalCows")),
            Column("От коров родилось живых телок", mapByDate("evtCalvAliveHeifersCows")),
            Column("От коров родилось живых быков", mapByDate("evtCalvAliveBullsCows")),
            Column("От коров родилось мертвых телок", mapByDate("evtCalvDeadHeifersCows")),
            Column("От коров родилось мертвых быков", mapByDate("evtCalvDeadBullsCows")),
            Column("% мертворожденности от коров", mapByDate("evtCalvDeadCowsPcnt")),
            Column("% рождаемости телок от коров", mapByDate("evtCalvAliveHeifersCowsPcnt")),
            Column("Абортировало коров", mapByDate("evtAbortCows")),
            Column("Абортировало нетелей", mapByDate("evtAbortHeifers")),
            Column("Мастит голов за месяц коров", mapByDate("evtMastForMonthCows")),
            Column("Хромота голов за месяц коров", mapByDate("evtLameForMonthCows")),
            Column("Хромота голов за месяц телок", mapByDate("evtLameForMonthHeifers")),
            Column("Задержаний последа лактация", mapByDate("evtRetPlacLact1")),
            Column("% задержаний последа у нетелей", mapByDate("evtRetPlacLact1Pcnt")),
            Column("Задержаний последа лактация > 1", mapByDate("evtRetPlacLactO1")),
            Column("% задержаний последа у коров", mapByDate("evtRetPlacLactO1Pcnt")),
            Column("Задержаний последа всего", mapByDate("evtRetPlacTotal")),
            Column("% задержаний последа", mapByDate("evtRetPlacTotalPcnt")),
            Column("Парезов лактация 1", mapByDate("evtParesLact1")),
            Column("% парезов у нетелей", mapByDate("evtParesLact1Pcnt")),
            Column("Парезов лактация > 1", mapByDate("evtParesLactO1")),
            Column("% парезов у коров", mapByDate("evtParesLactO1Pcnt")),
            Column("Парезов всего", mapByDate("evtParesTotal")),
            Column("% парезов", mapByDate("evtParesTotalPcnt")),
            Column("Кетозов лактация 1", mapByDate("evtKetosLact1")),
            Column("% кетозов у нетелей", mapByDate("evtKetosLact1Pcnt")),
            Column("Кетозов лактация > 1", mapByDate("evtKetosLactO1")),
            Column("% кетозов у коров", mapByDate("evtKetosLactO1Pcnt")),
            Column("Кетозов всего", mapByDate("evtKetosTotal")),
            Column("% кетозов", mapByDate("evtKetosTotalPcnt")),
            Column("Метритов", mapByDate("evtMetrit")),
            Column("% метритов", mapByDate("evtMetritPcnt")),
            Column("Переводов коров", mapByDate("evtMoveCows")),
            Column("Переводов телок", mapByDate("evtMoveHeifers")),
            Column("Вакцинация коров", mapByDate("evtVaccCows")),
            Column("Вакцинация телок", mapByDate("evtVaccHeifers")),
            Column("Расчистка копыт коров", mapByDate("evtFootrimCows")),
            Column("Расчистка копыт телок", mapByDate("evtFootrimHeifers")),
            Column("Продажа коров лактация 1 0-10 ДД", mapByDate("evtSoldCowsLact1010")),
            Column("Продажа коров лактация 1 11-30 ДД", mapByDate("evtSoldCowsLact11130")),
            Column("Продажа коров лактация 1 31-60 ДД", mapByDate("evtSoldCowsLact13160")),
            Column("Продажа коров лактация 1 61-120 ДД", mapByDate("evtSoldCowsLact161120")),
            Column("Продажа коров лактация 1 > 120 ДД", mapByDate("evtSoldCowsLact1O120")),
            Column("Продажа коров лактация 1 всего", mapByDate("evtSoldCowsLact1Total")),
            Column("Продажа коров лактация 2 0-10 ДД", mapByDate("evtSoldCowsLact2010")),
            Column("Продажа коров лактация 2 11-30 ДД", mapByDate("evtSoldCowsLact21130")),
            Column("Продажа коров лактация 2 31-60 ДД", mapByDate("evtSoldCowsLact23160")),
            Column("Продажа коров лактация 2 61-120 ДД", mapByDate("evtSoldCowsLact261120")),
            Column("Продажа коров лактация 2 > 120 ДД", mapByDate("evtSoldCowsLact2O120")),
            Column("Продажа коров лактация 2 всего", mapByDate("evtSoldCowsLact2Total")),
            Column("Продажа коров лактация > 2 0-10 ДД", mapByDate("evtSoldCowsLactO2010")),
            Column("Продажа коров лактация > 2 11-30 ДД", mapByDate("evtSoldCowsLactO21130")),
            Column("Продажа коров лактация > 2 31-60 ДД", mapByDate("evtSoldCowsLactO23160")),
            Column("Продажа коров лактация > 2 61-120 ДД", mapByDate("evtSoldCowsLactO261120")),
            Column("Продажа коров лактация > 2 > 120 ДД", mapByDate("evtSoldCowsLactO2O120")),
            Column("Продажа коров лактация > 2 всего", mapByDate("evtSoldCowsLactO2Total")),
            Column("Продажа коров всего", mapByDate("evtSoldCowsTotal")),
            Column("Продажа телок 0-2 мес", mapByDate("evtSoldHeifers02")),
            Column("Продажа телок 2-6 мес", mapByDate("evtSoldHeifers26")),
            Column("Продажа телок 6-12 мес", mapByDate("evtSoldHeifers612")),
            Column("Продажа телок > 12 мес", mapByDate("evtSoldHeifersO12")),
            Column("Продажа телок всего", mapByDate("evtSoldHeifersTotal")),
            Column("Продажа нетелей", mapByDate("evtSoldPheifers")),
            Column("Продажа быков", mapByDate("evtSoldBulls")),
            Column("Падеж коров лактация 1 0-10 ДД", mapByDate("evtDeadCowsLact1010")),
            Column("Падеж коров лактация 1 11-30 ДД", mapByDate("evtDeadCowsLact11130")),
            Column("Падеж коров лактация 1 31-60 ДД", mapByDate("evtDeadCowsLact13160")),
            Column("Падеж коров лактация 1 61-120 ДД", mapByDate("evtDeadCowsLact161120")),
            Column("Падеж коров лактация 1 > 120 ДД", mapByDate("evtDeadCowsLact1O120")),
            Column("Падеж коров лактация 1 всего", mapByDate("evtDeadCowsLact1Total")),
            Column("Падеж коров лактация 2 0-10 ДД", mapByDate("evtDeadCowsLact2010")),
            Column("Падеж коров лактация 2 11-30 ДД", mapByDate("evtDeadCowsLact21130")),
            Column("Падеж коров лактация 2 31-60 ДД", mapByDate("evtDeadCowsLact23160")),
            Column("Падеж коров лактация 2 61-120 ДД", mapByDate("evtDeadCowsLact261120")),
            Column("Падеж коров лактация 2 > 120 ДД", mapByDate("evtDeadCowsLact2O120")),
            Column("Падеж коров лактация 2 всего", mapByDate("evtDeadCowsLact2Total")),
            Column("Падеж коров лактация > 2 0-10 ДД", mapByDate("evtDeadCowsLactO2010")),
            Column("Падеж коров лактация > 2 11-30 ДД", mapByDate("evtDeadCowsLactO21130")),
            Column("Падеж коров лактация > 2 31-60 ДД", mapByDate("evtDeadCowsLactO23160")),
            Column("Падеж коров лактация > 2 61-120 ДД", mapByDate("evtDeadCowsLactO261120")),
            Column("Падеж коров лактация > 2 > 120 ДД", mapByDate("evtDeadCowsLactO2O120")),
            Column("Падеж коров лактация > 2 всего", mapByDate("evtDeadCowsLactO2Total")),
            Column("Падеж коров всего", mapByDate("evtDeadCowsTotal")),
            Column("Падеж телок 0-2 мес", mapByDate("evtDeadHeifers02")),
            Column("Падеж телок 2-6 мес", mapByDate("evtDeadHeifers26")),
            Column("Падеж телок 6-12 мес", mapByDate("evtDeadHeifers612")),
            Column("Падеж телок > 12 мес", mapByDate("evtDeadHeifersO12")),
            Column("Падеж телок всего", mapByDate("evtDeadHeifersTotal")),
            Column("Падеж нетелей", mapByDate("evtDeadPheifers")),
            Column("Падеж быков", mapByDate("evtDeadBulls")),
            Column("Индекс выявления охоты коров", mapByDate("brdHeatDetRateCow")),
            Column("Индекс выявления охоты телок", mapByDate("brdHeatDetRateHeif")),
            Column("Индекс оплодотворяемости коров", mapByDate("brdConcRateCow")),
            Column("Индекс оплодотворяемости телок", mapByDate("brdConcRateHeif")),
            Column("Индекс стельности коров", mapByDate("brdPregRateCow")),
            Column("Индекс стельности телок", mapByDate("brdPregRateHeif")),
            Column("Доз семени на стельную корову", mapByDate("brdStrawsPerPregCow")),
            Column("Доз семени на стельную телку", mapByDate("brdStrawsPerPregHeif")),
            Column("Валовой надой", mapByDate("mlkMilkSumYield")),
            Column("Надой 1 ф/к", mapByDate("mlkMilkPerCow")),
            Column("Надой 1 д/к", mapByDate("mlkMilkPerLactCow")),
            Column("KPI кормления", mapByDate("feedKpi"))
        )

    private fun mapByDate(name: String): List<Row> {
        val field = RptFarmSummaryHistory::class.java.getField(name)
        return items.map { Row(it.date, field.get(it)?.toString() ?: "0") }
    }

    @SerializedName("rpt_farm_summary_history")
    @Expose
    lateinit var items: List<RptFarmSummaryHistory>
}